include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - "**/generated_plugin_registrant.dart"
  errors:
    require_trailing_commas: error
    directives_ordering: error
    prefer_single_quotes: error
    always_declare_return_types: error
    prefer_relative_imports: error
    avoid_print: error
    unused_import: error
    unused_element: error
    unnecessary_import: error
    missing_return: error
    sized_box_for_whitespace: error

linter:
  rules:
    sized_box_for_whitespace: true
    require_trailing_commas: true
    directives_ordering: true
    prefer_single_quotes: true
    always_declare_return_types: true
    prefer_relative_imports: true
    avoid_print: true
    depend_on_referenced_packages: false
