include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - "**/generated_plugin_registrant.dart"
  errors:
    require_trailing_commas: error
    unused_import: error
    directives_ordering: error
    prefer_single_quotes: error
    always_declare_return_types: error

linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
    require_trailing_commas: true
    directives_ordering: true
