include: package:flutter_lints/flutter.yaml

linter:
  rules:
    use_key_in_widget_constructors: true
    avoid_print: false  
    prefer_single_quotes: true  
    always_declare_return_types: true 
    no_logic_in_create_state: true
    avoid_dynamic_calls: true
    lines_longer_than_80_chars: false
    leading_newlines_in_multiline_strings: true
    curly_braces_in_flow_control_structures: true
    cancel_subscriptions: true
    avoid_bool_literals_in_conditional_expressions: true
    require_trailing_commas: true
    prefer_relative_imports: true