workflows:
  default:
   name: Pay Flow
   scripts:
    - name: Get Flutter Packages
      script: flutter pub get
    - name: Build aab
      script: /
        CURRENT_BUILD_NUMER=$(google-play get-lasted-build-number --package-name "br.com.ismael.pay_flow")
        flutter build appbundle --release --build-number=$((CURRENT_BUILD_NUMER + 1))