workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "br.com.ismael.pay_flow"
        GOOGLE_PLAY_TRACK: production
        FCI_BUILD_NUMBER: 52
      groups:
        - keystore_credentials
        - google_play
      android_signing:
        - pay-flow-keystore
    scripts:
      - name: Set up local.properties
        script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Update version pubspec.yaml
        script: |
          chmod +x scripts/update_version.sh
          ./scripts/update_version.sh
      - name: Build AAB with Flutter
        script: |
          flutter build appbundle --release 
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - http.ismaeel@gmail.com
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: false
