workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      groups:
        - repo_credentials
        - google_play
      android_signing:
        - pay-flow-keystore
    scripts:
      #   - name: Set up local.properties
      #     script: |
      #       echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      # - name: Update version pubspec.yaml
      #   script: |
      #     chmod +x $CM_BUILD_DIR/scripts/update_version.sh
      #     cd $CM_BUILD_DIR
      #     ./scripts/update_version.sh
      - name: New release ShoreBird
        script: |
          curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash
          export PATH="/Users/builder/.shorebird/bin:$PATH"
          echo $SHOREBIRD_CREDENTIALS | base64 --decode > ~/.shorebird/credentials.json
          shorebird login --no-launch-browser
          yes | shorebird release android
      # - name: Build AAB with Flutter
      #   script: |
      #     flutter build appbundle --release --no-tree-shake-icons
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - http.ismaeel@gmail.com
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: production
        submit_as_draft: false
