workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    environment:
      android_signing:
        - pay-flow-keystore
      groups:
        - google_credentials
      vars:
        PACKAGE_NAME: "br.com.ismael.pay_flow"
        GOOGLE_PLAY_TRACK: "production"
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Dar permissão de execução
        script: |
          chmod +x scripts/update_version.sh
      - name: Run Slang + Run auto increment script build version
        script: |
          flutter pub get && flutter pub run slang
          scripts/update_version.sh
      - name: Build APK
        script: |
          flutter build apk
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - http.ismaeel@gmail.com
        notify:
          success: true
          failure: false
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: false
