name: pay_flow
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+7

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  # google_mobile_ads: ^2.0.1
  google_sign_in: ^5.4.1
  firebase_core: ^1.22.0
  firebase_crashlytics: ^2.8.10
  firebase_analytics: ^9.3.5
  firebase_performance: ^0.8.3
  flutter_masked_text2: ^0.9.1
  flutter_barcode_scanner: ^2.0.0
  flutter_screenutil: ^5.5.4
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  cached_network_image: ^3.2.2
  intl: ^0.17.0
  shimmer: ^2.0.0
  local_auth: ^2.1.2
  dio: ^4.0.6
  dartz: ^0.10.1

dev_dependencies:
  flutter_lints: ^2.0.1
  mocktail: ^0.3.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/i18n/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca-Regular.ttf
