name: pay_flow
description: A new Flutter project.

publish_to: "none"
version: 2.0.28+317

environment:
  sdk: ">=3.6.0"
  flutter: ">=3.27.1"

dependency_overrides:
  meta: ^1.12.0
  archive: ^3.6.1
  source_gen: ^1.5.0
  dart_style: ^3.0.1
  analyzer: ^5.2.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # STATE MANAGEMENT
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4

  # NETWORKING
  dio: ^5.7.0
  talker_dio_logger: ^4.6.0
  cached_network_image: ^3.4.1

  # ASSETS MANAGEMENT
  image_picker: ^1.1.2
  file_picker: ^8.1.7
  path_provider: ^2.1.5
  camera: ^0.11.0
  boleto_utils: ^1.0.3
  flutter_barcode_scanner: ^2.0.0

  # GOOGLE/APPLE
  sign_in_with_apple: ^6.1.4
  google_sign_in: ^6.2.2
  google_mobile_ads: ^5.2.0

  # FIREBASE
  firebase_core: ^3.10.0
  firebase_analytics: ^11.4.0
  firebase_crashlytics: ^4.3.0
  firebase_performance: ^0.10.1
  firebase_auth: ^5.4.0
  firebase_messaging: ^15.2.0

  # NOTIFICATIONS
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  flutter_timezone: ^4.0.0

  # UI
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  device_preview: ^1.2.0
  flutter_svg: ^2.0.17
  mask_text_input_formatter: ^2.9.0
  flutter_masked_text2: ^0.9.1
  lottie: ^3.3.1   
  
  # UTILITIES
  package_info_plus: ^8.1.2
  intl: 0.19.0
  url_launcher: ^6.3.1
  upgrader: ^11.3.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # DI/ARCHITECTURE
  get_it: ^8.0.3
  injectable: ^2.5.0
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # TESTING
  mocktail: ^1.0.4
  mocktail_image_network: ^1.2.0
  firebase_auth_mocks: ^0.14.1
  google_sign_in_mocks: ^0.3.0
  mockingjay: ^0.6.0
  faker: ^2.2.0

  # CODE GENERATION
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.2
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/lotties/
    - shorebird.yaml

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca-Regular.ttf
