name: pay_flow
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+7

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.4
  mocktail: ^0.3.0
  google_sign_in: ^5.3.1
  cached_network_image: ^3.2.1
  flutter_masked_text2: ^0.9.1
  flutter_barcode_scanner: ^2.0.0
  firebase_core: ^1.17.0
  firebase_crashlytics: ^2.8.0
  hasura_connect: ^4.0.0+2
  shimmer: ^2.0.0
  intl: ^0.17.0
  get: ^4.6.3
  uuid: ^3.0.6

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  integration_test :
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca-Regular.ttf
