name: pay_flow
description: A new Flutter project.

publish_to: "none"
version: 2.0.20+54

environment:
  sdk: ">=3.2.4 <4.0.0"
  # flutter: ">=3.16.8"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # STATE MANAGEMENT
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2

  # NETWORKING
  dio: ^5.4.0
  talker_dio_logger: ^4.0.0
  cached_network_image: ^3.3.1

  # ASSETS MANAGEMENT
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  path_provider: ^2.1.2
  camera: ^0.10.5+9
  boleto_utils: ^1.0.3
  flutter_barcode_scanner: ^2.0.0

  # GOOGLE/APPLE
  sign_in_with_apple: ^5.0.0
  google_sign_in: ^6.2.1
  google_mobile_ads: ^4.0.0

  # FIREBASE/ONESIGNAL
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.9
  firebase_performance: ^0.9.3+8
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  onesignal_flutter: ^5.0.4

  # UI
  cupertino_icons: ^1.0.6
  shimmer: ^3.0.0
  device_preview: ^1.1.0
  flutter_svg: ^2.0.9
  mask_text_input_formatter: ^2.8.0
  flutter_masked_text2: ^0.9.1
  lottie: ^3.0.0

  # UTILITIES
  package_info_plus: ^5.0.1
  intl: 0.18.1
  url_launcher: ^6.2.4
  upgrader: ^9.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # DI/ARCHITECTURE
  get_it: ^7.6.7
  injectable: ^2.3.2
  go_router: ^13.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # TESTING
  mocktail: ^1.0.3
  mocktail_image_network: ^1.1.0
  mockingjay: ^0.5.0
  faker: ^2.1.0

  # CODE GENERATION
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/lotties/
    - assets/mocks/
    - shorebird.yaml

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca-Regular.ttf
