name: pay_flow
description: A new Flutter project.

publish_to: "none"
version: 2.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.3
  boleto_utils: ^1.0.2
  google_mobile_ads: ^2.3.0
  google_sign_in: ^5.4.2
  firebase_core: ^2.4.1
  firebase_crashlytics: ^3.0.9
  firebase_messaging: ^14.2.1
  firebase_auth: ^4.2.4
  cloud_firestore: ^4.3.1
  flutter_screenutil: ^5.6.0
  flutter_barcode_scanner: ^2.0.0
  flutter_local_notifications: ^13.0.0
  # flutter_native_timezone: ^2.0.0
  freezed_annotation: ^2.2.0
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.3
  timezone: ^0.9.1
  pay: ^1.0.11
  intl: ^0.17.0
  get_it: ^7.2.0
  image_picker: ^0.8.6
  shimmer: ^2.0.0
  local_auth: ^2.1.3
  dio: ^4.0.6
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1
  json_serializable: ^6.5.4
  faker: ^2.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/i18n/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca-Regular.ttf
