name: pay_flow
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  hasura_connect: ^4.0.0+2
  google_sign_in: ^5.2.1
  camera: ^0.9.4+5
  shimmer: ^2.0.0
  get: ^4.6.1
  dartz: ^0.10.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  mocktail: ^0.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca-Regular.ttf
