name: pay_flow
description: A new Flutter project.

publish_to: "none"
version: 2.0.16+53

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  boleto_utils: ^1.0.2
  get_it: ^7.6.0
  google_sign_in: ^6.1.2
  google_mobile_ads: ^3.0.0
  firebase_core: ^2.13.0
  firebase_crashlytics: ^3.3.1
  firebase_messaging: ^14.6.1
  flutter_screenutil: ^5.8.2
  flutter_barcode_scanner: ^2.0.0
  flutter_masked_text2: ^0.9.1
  flutter_local_notifications: ^14.1.0
  freezed_annotation: ^2.2.0
  flutter_mobx: ^2.0.6+5
  mobx: ^2.2.0
  json_annotation: ^4.8.1
  package_info_plus: ^4.0.1
  timezone: ^0.9.2
  lottie: ^2.3.2
  shimmer: ^3.0.0
  intl: ^0.18.1
  dio: ^5.1.2
  pretty_dio_logger: ^1.3.1
  slang: ^3.17.0
  slang_flutter: ^3.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  faker: ^2.1.0
  mockito: ^5.4.1
  flutter_lints: ^2.0.1
  build_runner: ^2.4.4
  slang_build_runner: ^3.17.0
  mobx_codegen: ^2.3.0
  freezed: ^2.3.4
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/lotties/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca-Regular.ttf
