name: pay_flow
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+7

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_core: ^1.21.1
  firebase_crashlytics: ^2.8.9
  flutter_masked_text2: ^0.9.1
  flutter_barcode_scanner: ^2.0.0
  flutter_screenutil: ^5.5.3+2
  google_sign_in: ^5.4.1
  # google_mobile_ads: ^2.0.1
  intl: ^0.17.0
  shimmer: ^2.0.0
  cached_network_image: ^3.2.1
  dio: ^4.0.6

dev_dependencies:
  flutter_lints: ^2.0.1
  mocktail: ^0.3.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/i18n/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca-Regular.ttf
