name: pay_flow
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  google_sign_in: ^5.2.3
  hasura_connect: ^4.0.0+2
  flutter_barcode_scanner: ^2.0.0
  flutter_masked_text2: ^0.9.1
  flutter_dotenv: ^5.0.2
  intl: ^0.17.0
  shimmer: ^2.0.0
  get: ^4.6.1
  equatable: ^2.0.3
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  mocktail: ^0.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/hasura_settings.env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca-Regular.ttf
