// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFMN5n2B7ylb4RvTho7WHGkY2YgLixcE4',
    appId: '1:911161269065:android:82226b1c88dd3243275898',
    messagingSenderId: '911161269065',
    projectId: 'payflow-333802',
    storageBucket: 'payflow-333802.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVK4Ns1xMulJf3tS51Rje5XS_0PiI9gxM',
    appId: '1:911161269065:ios:e9b98dd1180d513c275898',
    messagingSenderId: '911161269065',
    projectId: 'payflow-333802',
    storageBucket: 'payflow-333802.appspot.com',
    androidClientId: '911161269065-2ivlmt3ivig9o27o3kjc04po2ej24lbn.apps.googleusercontent.com',
    iosClientId: '911161269065-1ug25ib2e4edevgmpieuaq7hp0fp2dd4.apps.googleusercontent.com',
    iosBundleId: 'br.com.ismael.payflow',
  );
}
